export const IRIS_POLL_LOOKBACK_HOURS = 6;
export const MILLISECONDS_PER_HOUR = 3_600_000;

export const IRIS_POLL_MAX_REPOSITORIES = 5;
export const IRIS_POLL_REPOSITORY_CONCURRENCY = 3;
export const IRIS_POLL_SOURCE_CONCURRENCY = 3;
export const IRIS_POLL_RELEASES_PER_PAGE = 10;
export const IRIS_POLL_COMMITS_PER_PAGE = 20;

export const IRIS_POLL_MAX_LINEAR_INTEGRATIONS = 3;
export const IRIS_POLL_LINEAR_ISSUE_LIMIT = 25;
export const IRIS_POLL_LINEAR_DESCRIPTION_LIMIT = 400;

export const IRIS_POLL_DIGEST_ITEMS_PER_SOURCE = 10;
export const IRIS_POLL_DIGEST_TITLE_LIMIT = 160;

export const GITHUB_API_VERSION_HEADER = "2022-11-28";
