export const GEO_TOOL_DEFAULT_DAYS = 30;
export const GEO_TOOL_MAX_DAYS = 365;
export const GEO_TOOL_DEFAULT_PROMPT_RESULT_LIMIT = 50;
export const GEO_TOOL_MAX_PROMPT_RESULT_LIMIT = 100;
export const GEO_TOOL_DEFAULT_COMPETITOR_LIMIT = 10;
export const GEO_TOOL_MAX_COMPETITOR_LIMIT = 25;
