import type { BeaconSignature } from "./types";

export const BEACON_SIGNATURES: readonly BeaconSignature[] = [
  {
    agent: "GPTBot",
    vendor: "OpenAI",
    category: "training-crawler",
    userAgents: ["GPTBot"],
    confidence: "verified",
    verification: "https://openai.com/gptbot.json",
    source: "https://developers.openai.com/api/docs/bots",
  },
  {
    agent: "OAI-SearchBot",
    vendor: "OpenAI",
    category: "search-index",
    userAgents: ["OAI-SearchBot"],
    confidence: "verified",
    verification: "https://openai.com/searchbot.json",
    source: "https://developers.openai.com/api/docs/bots",
  },
  {
    agent: "ChatGPT-User",
    vendor: "OpenAI",
    category: "assistant-browse",
    userAgents: ["ChatGPT-User"],
    confidence: "verified",
    verification: "https://openai.com/chatgpt-user.json",
    source: "https://developers.openai.com/api/docs/bots",
  },
  {
    agent: "OAI-AdsBot",
    vendor: "OpenAI",
    category: "search-index",
    userAgents: ["OAI-AdsBot"],
    confidence: "verified",
    verification: "https://openai.com/adsbot.json",
    source: "https://developers.openai.com/api/docs/bots",
  },
  {
    agent: "Claude Code",
    vendor: "Anthropic",
    category: "assistant-browse",
    userAgents: ["claude-code/"],
    confidence: "reported",
    verification: null,
    source: "https://github.com/monperrus/crawler-user-agents",
  },
  {
    agent: "Claude-SearchBot",
    vendor: "Anthropic",
    category: "search-index",
    userAgents: ["Claude-SearchBot"],
    confidence: "verified",
    verification: "https://claude.com/crawling/bots.json",
    source: "https://support.claude.com/en/articles/8896518",
  },
  {
    agent: "Claude-User",
    vendor: "Anthropic",
    category: "assistant-browse",
    userAgents: ["Claude-User"],
    confidence: "verified",
    verification: "https://claude.com/crawling/bots.json",
    source: "https://support.claude.com/en/articles/8896518",
  },
  {
    agent: "ClaudeBot",
    vendor: "Anthropic",
    category: "training-crawler",
    userAgents: ["ClaudeBot"],
    confidence: "verified",
    verification: "https://claude.com/crawling/bots.json",
    source: "https://support.claude.com/en/articles/8896518",
  },
  {
    agent: "anthropic-ai",
    vendor: "Anthropic",
    category: "training-crawler",
    userAgents: ["anthropic-ai"],
    confidence: "reported",
    verification: null,
    source:
      "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json",
  },
  {
    agent: "claude-web",
    vendor: "Anthropic",
    category: "assistant-browse",
    userAgents: ["claude-web"],
    confidence: "reported",
    verification: null,
    source:
      "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json",
  },
  {
    agent: "PerplexityBot",
    vendor: "Perplexity",
    category: "search-index",
    userAgents: ["PerplexityBot"],
    confidence: "verified",
    verification: "https://www.perplexity.ai/perplexitybot.json",
    source: "https://docs.perplexity.ai/guides/bots",
  },
  {
    agent: "Perplexity-User",
    vendor: "Perplexity",
    category: "assistant-browse",
    userAgents: ["Perplexity-User"],
    confidence: "verified",
    verification: "https://www.perplexity.ai/perplexity-user.json",
    source: "https://docs.perplexity.ai/guides/bots",
  },
  {
    agent: "Google-CloudVertexBot",
    vendor: "Google",
    category: "training-crawler",
    userAgents: ["Google-CloudVertexBot"],
    confidence: "verified",
    verification:
      "https://developers.google.com/static/search/apis/ipranges/special-crawlers.json",
    source:
      "https://developers.google.com/search/docs/crawling-indexing/google-special-case-crawlers",
  },
  {
    agent: "GoogleOther-Image",
    vendor: "Google",
    category: "training-crawler",
    userAgents: ["GoogleOther-Image"],
    confidence: "verified",
    verification:
      "https://developers.google.com/static/search/apis/ipranges/special-crawlers.json",
    source:
      "https://developers.google.com/search/docs/crawling-indexing/google-special-case-crawlers",
  },
  {
    agent: "GoogleOther-Video",
    vendor: "Google",
    category: "training-crawler",
    userAgents: ["GoogleOther-Video"],
    confidence: "verified",
    verification:
      "https://developers.google.com/static/search/apis/ipranges/special-crawlers.json",
    source:
      "https://developers.google.com/search/docs/crawling-indexing/google-special-case-crawlers",
  },
  {
    agent: "GoogleOther",
    vendor: "Google",
    category: "training-crawler",
    userAgents: ["GoogleOther"],
    confidence: "heuristic",
    verification:
      "https://developers.google.com/static/search/apis/ipranges/special-crawlers.json",
    source:
      "https://developers.google.com/search/docs/crawling-indexing/google-special-case-crawlers",
  },
  {
    agent: "Bytespider",
    vendor: "ByteDance",
    category: "training-crawler",
    userAgents: ["Bytespider"],
    confidence: "reported",
    verification: null,
    source:
      "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json",
  },
  {
    agent: "Amazonbot",
    vendor: "Amazon",
    category: "training-crawler",
    userAgents: ["Amazonbot"],
    confidence: "verified",
    verification: "https://developer.amazon.com/amazonbot/ip-addresses/",
    source: "https://developer.amazon.com/amazonbot",
  },
  {
    agent: "Applebot",
    vendor: "Apple",
    category: "search-index",
    userAgents: ["Applebot/"],
    confidence: "verified",
    verification: "https://search.developer.apple.com/applebot.json",
    source: "https://support.apple.com/en-us/119829",
  },
  {
    agent: "cohere-training-data-crawler",
    vendor: "Cohere",
    category: "training-crawler",
    userAgents: ["cohere-training-data-crawler"],
    confidence: "reported",
    verification: null,
    source:
      "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json",
  },
  {
    agent: "cohere-ai",
    vendor: "Cohere",
    category: "assistant-browse",
    userAgents: ["cohere-ai"],
    confidence: "reported",
    verification: null,
    source:
      "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json",
  },
  {
    agent: "meta-externalagent",
    vendor: "Meta",
    category: "training-crawler",
    userAgents: ["meta-externalagent"],
    confidence: "verified",
    verification: null,
    source:
      "https://developers.facebook.com/docs/sharing/webmasters/web-crawlers/",
  },
  {
    agent: "meta-externalfetcher",
    vendor: "Meta",
    category: "assistant-browse",
    userAgents: ["meta-externalfetcher"],
    confidence: "verified",
    verification: null,
    source:
      "https://developers.facebook.com/docs/sharing/webmasters/web-crawlers/",
  },
  {
    agent: "FacebookBot",
    vendor: "Meta",
    category: "training-crawler",
    userAgents: ["FacebookBot"],
    confidence: "reported",
    verification: null,
    source:
      "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json",
  },
  {
    agent: "DuckAssistBot",
    vendor: "DuckDuckGo",
    category: "assistant-browse",
    userAgents: ["DuckAssistBot"],
    confidence: "verified",
    verification: "https://duckduckgo.com/duckassistbot.json",
    source:
      "https://duckduckgo.com/duckduckgo-help-pages/results/duckassistbot/",
  },
  {
    agent: "LinerBot",
    vendor: "Liner",
    category: "search-index",
    userAgents: ["LinerBot"],
    confidence: "verified",
    verification: "https://docs.getliner.com/linerbot.json",
    source: "https://docs.getliner.com/docs/linerbot",
  },
  {
    agent: "YouBot",
    vendor: "You.com",
    category: "search-index",
    userAgents: ["YouBot"],
    confidence: "verified",
    verification: "https://you.com/docs/youbot",
    source: "https://you.com/docs/youbot",
  },
  {
    agent: "MistralAI-User",
    vendor: "Mistral",
    category: "assistant-browse",
    userAgents: ["MistralAI-User"],
    confidence: "verified",
    verification: "https://mistral.ai/mistralai-user-ips.json",
    source: "https://docs.mistral.ai/robots",
  },
  {
    agent: "CCBot",
    vendor: "Common Crawl",
    category: "training-crawler",
    userAgents: ["CCBot"],
    confidence: "verified",
    verification: "https://index.commoncrawl.org/ccbot.json",
    source: "https://commoncrawl.org/ccbot",
  },
  {
    agent: "Diffbot",
    vendor: "Diffbot",
    category: "training-crawler",
    userAgents: ["Diffbot"],
    confidence: "reported",
    verification: null,
    source: "https://www.diffbot.com/docs/crawl/faq/robots-txt",
  },
  {
    agent: "Timpibot",
    vendor: "Timpi",
    category: "training-crawler",
    userAgents: ["Timpibot"],
    confidence: "reported",
    verification: null,
    source:
      "https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json",
  },
  {
    agent: "Devin",
    vendor: "Cognition",
    category: "assistant-browse",
    userAgents: ["Devin/"],
    confidence: "reported",
    verification: null,
    source: "https://radar.cloudflare.com/traffic/verified-bots",
  },
  {
    agent: "GoogleAgent-URLContext",
    vendor: "Google",
    category: "assistant-browse",
    userAgents: ["GoogleAgent-URLContext", "Google-Gemini-CLI"],
    confidence: "reported",
    verification: null,
    source:
      "https://www.checklyhq.com/blog/state-of-ai-agent-content-negotation/",
  },
  {
    agent: "Trae-Agent",
    vendor: "ByteDance",
    category: "assistant-browse",
    userAgents: ["Trae-Agent"],
    confidence: "reported",
    verification: null,
    source: "https://knownagents.com/agents/trae",
  },
  {
    agent: "omgili",
    vendor: "Webz.io",
    category: "training-crawler",
    userAgents: ["omgilibot", "omgili"],
    confidence: "verified",
    verification: null,
    source:
      "https://webz.io/blog/web-data/what-is-the-omgili-bot-and-why-is-it-crawling-your-website/",
  },
];
