import { db } from "@notra/db/drizzle";
import { brandReferences, brandSettings, skills } from "@notra/db/schema";
import type { Box } from "@upstash/box";
import { and, desc, eq } from "drizzle-orm";
import { withBoxRetry } from "./repo-image-box";

type RepoImageBox = Awaited<ReturnType<typeof Box.create>>;

const BRAND_IDENTITY_SKILL_DIR = ".agents/skills/brand-identity";
const BRAND_IDENTITY_SKILL_PATH = `${BRAND_IDENTITY_SKILL_DIR}/SKILL.md`;
const HUMANIZER_SKILL_DIR = ".agents/skills/humanizer";
const HUMANIZER_SKILL_PATH = `${HUMANIZER_SKILL_DIR}/SKILL.md`;
const BRAND_REFERENCE_LIMIT = 30;
const BRAND_REFERENCE_CONTENT_LIMIT = 3000;
const LINE_SPLIT_REGEX = /\r?\n/;
const FRONTMATTER_START_REGEX = /^---\r?\n/;

export async function injectBrandIdentitySkill(params: {
  box: RepoImageBox;
  organizationId: string;
  brandIdentityId?: string;
}) {
  const skill = await buildBrandIdentitySkillContent({
    organizationId: params.organizationId,
    brandIdentityId: params.brandIdentityId,
  });

  if (!skill) {
    return null;
  }

  await writeSandboxSkill({
    box: params.box,
    dir: BRAND_IDENTITY_SKILL_DIR,
    path: BRAND_IDENTITY_SKILL_PATH,
    content: skill.content,
  });

  return skill.brandIdentityId;
}

export async function injectHumanizerSkill(params: {
  box: RepoImageBox;
  organizationId: string;
}) {
  const skill = await db.query.skills.findFirst({
    where: and(
      eq(skills.organizationId, params.organizationId),
      eq(skills.name, "humanizer")
    ),
  });

  if (!skill) {
    return;
  }

  await writeSandboxSkill({
    box: params.box,
    dir: HUMANIZER_SKILL_DIR,
    path: HUMANIZER_SKILL_PATH,
    content: renderSandboxSkillContent(skill),
  });
}

async function writeSandboxSkill(params: {
  box: RepoImageBox;
  dir: string;
  path: string;
  content: string;
}) {
  const encoded = Buffer.from(params.content, "utf8").toString("base64");
  await withBoxRetry(() =>
    params.box.exec.command(
      `mkdir -p ${params.dir} && printf '%s' '${encoded}' | base64 -d > ${params.path}`
    )
  );
}

function renderSandboxSkillContent(skill: typeof skills.$inferSelect) {
  const content = skill.content.trim();
  if (FRONTMATTER_START_REGEX.test(content)) {
    return `${content}\n`;
  }

  return `---
name: ${JSON.stringify(skill.name)}
description: ${JSON.stringify(skill.description.trim())}
---

${content}
`;
}

async function buildBrandIdentitySkillContent(params: {
  organizationId: string;
  brandIdentityId?: string;
}) {
  const identity = params.brandIdentityId
    ? await db.query.brandSettings.findFirst({
        where: and(
          eq(brandSettings.id, params.brandIdentityId),
          eq(brandSettings.organizationId, params.organizationId)
        ),
      })
    : await db.query.brandSettings.findFirst({
        where: eq(brandSettings.organizationId, params.organizationId),
        orderBy: [desc(brandSettings.isDefault), desc(brandSettings.createdAt)],
      });

  if (!identity) {
    return null;
  }

  const references = await db.query.brandReferences.findMany({
    where: eq(brandReferences.brandSettingsId, identity.id),
    orderBy: [desc(brandReferences.createdAt)],
    limit: BRAND_REFERENCE_LIMIT,
  });

  const fields = [
    ["Brand identity id", identity.id],
    ["Identity name", identity.name],
    ["Default identity", identity.isDefault ? "Yes" : "No"],
    ["Website URL", identity.websiteUrl],
    ["Company name", identity.companyName],
    ["Company description", identity.companyDescription],
    ["Tone profile", identity.toneProfile],
    ["Custom tone", identity.customTone],
    ["Custom instructions", identity.customInstructions],
    ["Audience", identity.audience],
    ["Language", identity.language],
  ]
    .map(([label, value]) => `- ${label}: ${formatSkillValue(value)}`)
    .join("\n");

  const referenceSection =
    references.length === 0
      ? "No saved writing references are attached to this brand identity."
      : references
          .map((reference, index) => {
            const note = reference.note?.trim()
              ? `\nNote:\n${toMarkdownQuote(reference.note)}\n`
              : "";
            return `### Reference ${index + 1}\n\n- Type: ${reference.type}\n- Applies to: ${reference.applicableTo.join(", ")}${note}\nContent:\n${toMarkdownQuote(truncateReference(reference.content))}`;
          })
          .join("\n\n");

  const content = `---
name: brand-identity
description: Apply the selected Notra brand identity and saved brand reference material injected from the Notra database for this sandbox run.
---

# Notra Brand Identity

This skill was generated by Notra for this sandbox. It contains the selected brand identity and saved brand reference material from the database.

## How To Use This Skill

- Treat the brand identity below as the publishing identity for this image.
- Use repository, PR, commit, and file data only as factual source material.
- Match the brand's company context, audience, tone, language, and custom instructions.
- Use saved references as style evidence: vocabulary, rhythm, structure, emphasis, and what the brand avoids.
- Do not copy distinctive reference lines verbatim into new image text.
- If source names differ from the brand identity, keep the selected brand identity and frame source data as contributions, integrations, fixes, or relevant product work.

## Selected Brand Identity

${fields}

## Saved Brand References

${referenceSection}
`;

  return { brandIdentityId: identity.id, content };
}

function formatSkillValue(value: unknown) {
  if (typeof value !== "string") {
    return value === null || value === undefined ? "Not set" : String(value);
  }

  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : "Not set";
}

function truncateReference(value: string) {
  if (value.length <= BRAND_REFERENCE_CONTENT_LIMIT) {
    return value;
  }

  return `${value.slice(0, BRAND_REFERENCE_CONTENT_LIMIT).trimEnd()}\n[Truncated]`;
}

function toMarkdownQuote(value: string) {
  return value
    .trim()
    .split(LINE_SPLIT_REGEX)
    .map((line) => `> ${line}`)
    .join("\n");
}
