export const COPY = {
  coldOpen: "You shipped. Now show it.",
  onePromptTitle: "From merged PR.",
  onePromptSub: "To launch visual, in your brand.",
  pixelPerfectSub: "Real logos and app components, vector sharp.",
  designersTitle: "Built with designers in mind.",
  designersSub: "Straight from your repo to your canvas.",
  disclaimer: "A real image Notra generated for emdash.",
  toastTitle: "Copied for Paper",
  toastBody: "Ready to paste into your canvas.",
  layersSub: "Real text, frames, and shapes. Not a flat image.",
  editSub: "It's real text. Just retype it.",
  targets: "Works with Paper and Figma.",
  endTitleLead: "Image generation. Live",
  endTitleAccent: "now.",
  endUrl: "usenotra.com",
  affiliation: "Notra is not affiliated with Paper or Figma.",
  contentTitle: "Introducing Image Generation",
  windowTitle: "Custom sounds for agent events",
} as const;
