import type { DesignSystemCatalogItem } from "@/types/design-system-catalog";

export const DESIGN_SYSTEM_CATALOG: DesignSystemCatalogItem[] = [
  {
    id: "colors",
    number: "01",
    label: "Colors",
    href: "/design-system#colors",
    level: "group",
  },
  {
    id: "buttons",
    number: "02",
    label: "Buttons & Badges",
    href: "/design-system#buttons",
    level: "section",
  },
  {
    id: "forms",
    number: "03",
    label: "Forms & Inputs",
    href: "/design-system#forms",
    level: "section",
  },
  {
    id: "navigation",
    number: "04",
    label: "Navigation & Overlays",
    href: "/design-system#navigation",
    level: "section",
  },
  {
    id: "feedback",
    number: "05",
    label: "Feedback & Status",
    href: "/design-system#feedback",
    level: "section",
  },
  {
    id: "data-display",
    number: "06",
    label: "Data Display",
    href: "/design-system#data-display",
    level: "section",
  },
  {
    id: "rich-interactions",
    number: "07",
    label: "Rich Interactions",
    href: "/design-system#rich-interactions",
    level: "section",
  },
  {
    id: "identity",
    number: "08",
    label: "Identity & Layout",
    href: "/design-system#identity",
    level: "section",
  },
  {
    id: "utility",
    number: "09",
    label: "Utility Elements",
    href: "/design-system#utility",
    level: "section",
  },
  {
    id: "social",
    number: "10",
    label: "Social Previews",
    href: "/design-system#social",
    level: "section",
  },
  {
    id: "onboarding",
    number: "11",
    label: "Onboarding",
    href: "/design-system#onboarding",
    level: "section",
  },
  {
    id: "braille-loader",
    number: "12",
    label: "Braille Loader",
    href: "/design-system#braille-loader",
    level: "section",
  },
  {
    id: "claude-session",
    number: "13",
    label: "Claude · Session",
    href: "/design-system#claude-session",
    level: "group",
  },
  {
    id: "claude-header",
    number: "14",
    label: "Claude · Header",
    href: "/design-system#claude-header",
    level: "section",
  },
  {
    id: "claude-messages",
    number: "15",
    label: "Claude · Messages",
    href: "/design-system#claude-messages",
    level: "section",
  },
  {
    id: "claude-todos",
    number: "16",
    label: "Claude · Todos",
    href: "/design-system#claude-todos",
    level: "section",
  },
  {
    id: "claude-tools",
    number: "17",
    label: "Claude · Tools",
    href: "/design-system#claude-tools",
    level: "section",
  },
  {
    id: "claude-modes",
    number: "18",
    label: "Claude · Modes",
    href: "/design-system#claude-modes",
    level: "section",
  },
  {
    id: "claude-effort",
    number: "19",
    label: "Claude · Effort",
    href: "/design-system#claude-effort",
    level: "section",
  },
  {
    id: "claude-playground",
    number: "20",
    label: "Claude · Playground",
    href: "/design-system#claude-playground",
    level: "section",
  },
  {
    id: "codex-session",
    number: "21",
    label: "Codex · Session",
    href: "/design-system#codex-session",
    level: "group",
  },
  {
    id: "codex-header",
    number: "22",
    label: "Codex · Header",
    href: "/design-system#codex-header",
    level: "section",
  },
  {
    id: "codex-messages",
    number: "23",
    label: "Codex · Messages",
    href: "/design-system#codex-messages",
    level: "section",
  },
  {
    id: "codex-exec",
    number: "24",
    label: "Codex · Exec",
    href: "/design-system#codex-exec",
    level: "section",
  },
  {
    id: "codex-composer",
    number: "25",
    label: "Codex · Composer",
    href: "/design-system#codex-composer",
    level: "section",
  },
  {
    id: "chatgpt-thread",
    number: "26",
    label: "ChatGPT · Thread",
    href: "/design-system#chatgpt-thread",
    level: "group",
  },
  {
    id: "chatgpt-user",
    number: "27",
    label: "ChatGPT · User",
    href: "/design-system#chatgpt-user",
    level: "section",
  },
  {
    id: "chatgpt-assistant",
    number: "28",
    label: "ChatGPT · Assistant",
    href: "/design-system#chatgpt-assistant",
    level: "section",
  },
  {
    id: "chatgpt-models",
    number: "29",
    label: "ChatGPT · Models",
    href: "/design-system#chatgpt-models",
    level: "section",
  },
  {
    id: "chatgpt-playground",
    number: "30",
    label: "ChatGPT · Playground",
    href: "/design-system#chatgpt-playground",
    level: "section",
  },
  {
    id: "claude-chat-thread",
    number: "31",
    label: "Claude chat · Thread",
    href: "/design-system#claude-chat-thread",
    level: "group",
  },
  {
    id: "claude-chat-user",
    number: "32",
    label: "Claude chat · User",
    href: "/design-system#claude-chat-user",
    level: "section",
  },
  {
    id: "claude-chat-assistant",
    number: "33",
    label: "Claude chat · Assistant",
    href: "/design-system#claude-chat-assistant",
    level: "section",
  },
  {
    id: "claude-chat-models",
    number: "34",
    label: "Claude chat · Models",
    href: "/design-system#claude-chat-models",
    level: "section",
  },
  {
    id: "claude-chat-playground",
    number: "35",
    label: "Claude chat · Playground",
    href: "/design-system#claude-chat-playground",
    level: "section",
  },
];

export const DESIGN_SYSTEM_CATALOG_BY_ID = Object.fromEntries(
  DESIGN_SYSTEM_CATALOG.map((item) => [item.id, item])
) as Record<string, DesignSystemCatalogItem>;
