export const EVE_AGENT_SERVICE_USERNAME = "notra-dashboard";
export const EVE_AGENT_ORGANIZATION_HEADER = "x-notra-organization-id";
export const AGENT_RUN_POLL_INTERVAL_SECONDS = 30;
export const AGENT_RUN_SOFT_LIMIT_POLLS = 30;
export const AGENT_RUN_HARD_LIMIT_POLLS = 60;
export const AGENT_RUN_HARD_LIMIT_MS =
  AGENT_RUN_HARD_LIMIT_POLLS * AGENT_RUN_POLL_INTERVAL_SECONDS * 1000;
export const WEBSITE_REACHABILITY_TIMEOUT_MS = 5000;
export const SLACK_CHANNEL_NAME_MAX_LENGTH = 80;
export const SLACK_CHANNEL_PREFIX = "notra-";
