export const AGENT_RUN_BACKEND_SLEEP_SECONDS = 30;
export const AGENT_RUN_SOFT_LIMIT_POLLS = 30;
export const AGENT_RUN_HARD_LIMIT_POLLS = 60;
export const AGENT_RUN_HARD_LIMIT_MS =
  AGENT_RUN_HARD_LIMIT_POLLS * AGENT_RUN_BACKEND_SLEEP_SECONDS * 1000;
export const AGENT_RUN_REFETCH_INTERVAL_MS = 10_000;
export const AGENT_RUN_STALE_TIME_MS = 60_000;
export const SUGGESTIONS_STALE_TIME_MS = 300_000;
export const WEBSITE_REACHABILITY_TIMEOUT_MS = 5000;
export const WEBSITE_REACHABILITY_MAX_REDIRECTS = 5;
export const EVE_ACCENT_COLOR = "#9333EA";
export const EVE_CREATE_SESSION_ROUTE_PATH = "/eve/v1/session";
export const EVE_SESSION_TASK_MODE = "task";
export const TRAILING_SLASH_PATTERN = /\/$/;
export const WWW_PREFIX_PATTERN = /^www\./;
export const SERVER_ERROR_STATUS = 500;
