export const RESERVED_ORGANIZATION_SLUGS = [
  "api",
  "auth",
  "login",
  "signup",
  "forgot-password",
  "reset-password",
  "invitation",
  "callback",
  "onboarding",
  "dashboard",
  "rpc",
  "design-system",
  "settings",
  "admin",
  "help",
  "support",
  "docs",
  "blog",
  "about",
  "terms",
  "privacy",
  "contact",
] as const;

export const INVITATION_EXPIRY_MS = 7 * 24 * 60 * 60 * 1000;
